$call start https://www.census.gov/data/datasets/1993/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1994/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1995/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1996/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1997/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1998/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/1999/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/200/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2001/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2002/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2003/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2004/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2005/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2006/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2007/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2008/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2009/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2010/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2011/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2012/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2013/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2014/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2015/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2016/econ/local/public-use-datasets.html
*.$call start https://www.census.gov/data/datasets/2017/econ/local/public-use-datasets.html
*.$call start https://www.census.gov/data/datasets/2018/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2019/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2020/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2021/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2022/econ/local/public-use-datasets.html
$call start https://www.census.gov/data/datasets/2023/econ/local/public-use-datasets.html